- README.md
- src/rabbit_stomp_frame.erl
- test/src/destinations.py
- test/src/parsing.py
See #17. Also upgrades the test suite and ports one low test that was failing after the LF addition for no good reason.
> Added a newline character at the end of the frame

- test/src/rabbit_stomp_publish_test.erl
It must be merged **after** rabbitmq/rabbitmq-server#254.
References rabbitmq/rabbitmq-server#233.
> Support the new Time API in Erlang 18.0

- include/rabbit_stomp_headers.hrl
- src/rabbit_stomp_frame.erl
- src/rabbit_stomp_util.erl
- test/src/parsing.py
- test/src/redelivered.py
- test/src/test.py
Fixes https://github.com/rabbitmq/rabbitmq-stomp/issues/21.
> added redelivered flag in MESSAGE frame headers

- src/rabbit_stomp_frame.erl
- src/rabbit_stomp_processor.erl
- src/rabbitmq_stomp.app.src
- test/src/rabbit_stomp_test_frame.erl
> Make trailing LF character optional

- include/rabbit_stomp_headers.hrl
- src/rabbit_stomp_processor.erl
- src/rabbit_stomp_util.erl
- test/src/test.py
- test/src/x_queue_name.py
Fixes https://github.com/rabbitmq/rabbitmq-stomp/issues/43.
> implemented user generated queue names for /exchange & /topic destinations

- src/rabbit_stomp_client_sup.erl
- src/rabbit_stomp_reader.erl
- src/rabbit_stomp_sup.erl
- test/src/rabbit_stomp_test.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/260.
> Use Ranch for TCP acceptor pool

- src/rabbitmq_stomp.app.src
https://github.com/rabbitmq/rabbitmq-server/issues/453
> Remove unneeded TCP options from config in .app.src file

- src/rabbit_stomp_sup.erl
- src/rabbitmq_stomp.app.src
Part of https://github.com/rabbitmq/rabbitmq-server/issues/528
> Make number of Ranch acceptors configurable

- src/rabbit_stomp_reader.erl
> handle client_timeout in handle_cast

- src/rabbit_stomp_reader.erl
> Handling of resource alarm message

- src/rabbit_stomp_processor.erl
- src/rabbit_stomp_reader.erl
Fixes #72,
Requires Web STOMP changes: https://github.com/rabbitmq/rabbitmq-web-stomp/issues/48.
> Move heartbeats logic to stomp_reader

- priv/schema/rabbitmq_stomp.schema
- test/src/queue_properties.py
- test/src/x_queue_name.py
Schema for https://github.com/rabbitmq/rabbitmq-server/issues/550.
> cuttlefish schema

- examples/ruby/amq-sender.rb
- examples/ruby/exchange-receiver.rb
- examples/ruby/exchange-sender.rb
- examples/ruby/temp-queue-client.rb
- examples/ruby/temp-queue-service.rb
Here is the results of each examples that is added by this PR.
https://gist.github.com/userlocalhost2000/9cd2d67a04ed8e794976
https://gist.github.com/userlocalhost2000/0d5d002a11eb89a71fb9
https://gist.github.com/userlocalhost2000/d05bbd6466a811527991
Would you please tell me the points where I should correct?
> Added some examples in Ruby (for #78)

- src/rabbit_stomp_processor.erl
- src/rabbitmq_stomp.app.src
- test/src/parsing.py
> Introduce rabbitmq_stomp.hide_server_info

- src/rabbitmq_stomp.app.src
Related to https://github.com/rabbitmq/rabbitmq-server/pull/776
Part of https://github.com/rabbitmq/rabbitmq-server/issues/735
> Stub for broker_version_requirements

- .travis.yml
- test/src/rabbit_stomp_publish_test.erl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/798
and
https://github.com/rabbitmq/rabbitmq-server/issues/546
> Do not use time_compat

- src/rabbit_stomp.erl
- src/rabbit_stomp_processor.erl
Part of https://github.com/rabbitmq/rabbitmq-web-stomp/issues/60
> Small changes for Web STOMP

- test/amqqueue_SUITE.erl
Part of https://github.com/rabbitmq/rabbitmq-event-exchange/issues/10
> Pass user who performed the action to test fixtures

- src/rabbit_stomp_processor.erl
- test/topic_SUITE.erl
Part of rabbitmq/rabbitmq-server#1085
> Add topic authorisation for consumption

- Makefile
- rabbitmq-components.mk
- src/rabbit_stomp_reader.erl
- src/rabbit_stomp_sup.erl
- test/proxy_protocol_SUITE.erl
Part of rabbitmq/rabbitmq-server#589
> Add support for proxy protocol

- priv/schema/rabbitmq_stomp.schema
Part of rabbitmq/rabbitmq-server#589
> Add proxy protocol Cuttlefish option mapping

- src/rabbit_stomp_reader.erl
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/45
> Default to 0 for stats calculation

- src/rabbit_stomp_processor.erl
- src/rabbit_stomp_reader.erl
- src/rabbit_stomp_util.erl
Part of rabbitmq/rabbitmq-web-stomp#75.
[#144738809]
> Make sure maybe_delete_durable_sub/3 handles server-initiated cancelation

- Makefile
- rabbitmq-components.mk
- src/rabbit_stomp_client_sup.erl
- src/rabbit_stomp_reader.erl
- src/rabbit_stomp_sup.erl
This set of PRs is ready. Full set listed in https://github.com/rabbitmq/rabbitmq-common/pull/279
Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.
A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.
If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.
What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating …
> Use the built-in Ranch PROXY protocol support

- src/rabbit_stomp_reader.erl
Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.
A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.
If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.
What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here …
> Use {active,once} instead of async_recv

- Makefile
- priv/schema/rabbitmq_stomp.schema
- src/rabbit_stomp_processor.erl
- test/config_schema_SUITE_data/rabbitmq_stomp.snippets
- test/topic_SUITE.erl
> Add rabbitmq_stomp.default_topic_exchange configuration parameter

- README.md
> [README] Fixed rabbitmq-plugins link

- src/rabbit_stomp_processor.erl
> Remove use of dict: module

- priv/schema/rabbitmq_stomp.schema
- test/config_schema_SUITE_data/rabbitmq_stomp.snippets
> Add support for hide_server_info in rabbitmq.conf

- src/rabbit_stomp_processor.erl
- src/rabbit_stomp_reader.erl
Fixes rabbitmq/rabbitmq-web-stomp#116
> Export ssl_login_name
