.gitignore, src/rabbit_stomp_reader.erl, test/src/rabbit_stomp_test.erl
Fixes #7.
When we encounter a socket or parsing error, we need to make sure to shoot down processor. Otherwise we leak direct Erlang client connections. Which in turn exposed interesting edge cases such as https://github.com/rabbitmq/rabbitmq-management/issues/29.
Some background on why we fix it in this particular way:
* We want to avoid "scary" crash reports in the SASL log on network-related exceptions (or even parsing errors).
* We want to give the processor some time to finish what it's been doing.
So linking won't work.
To test this manually, connect to the server via netcat as explained [in the STOMP plugin documentation](https://www.rabbitmq.com/stomp.html) but after sending a `CONNECT` frame, send some garbage and a few new lines. You will see a parsing error in the log.
For …
=> Terminate STOMP processor when reader exits due to an exception

src/rabbit_stomp_frame.erl
According to https://stomp.github.io/stomp-specification-1.1.html#Standard_Headers there are three frame types, that can send this header, and only one of them (if I'm not mistaken) is used on the clientside - SEND. It would be great if this header would be ignored for the rest of the client commands.
Specifically, it causes an issue when attempting to ACK a frame that has been previously read in PHP.
Checkout the default code for the stomp extension http://php.net/manual/en/stomp.ack.php. Here is a slightly modified version with a workaround:
```php
<?php
try {
$client = new Stomp('tcp://localhost:61613', 'guest', 'guest');
} catch(StompException $exception) {
printf("Connection failed: %s\n", $e->getMessage());
exit(1);
}
$queue = '/queue/test-queue';
$client->subscribe($queue);
$msg = …
```
=> Only process the content-length header on the SEND command

.gitignore, deps/pika/Makefile, include/rabbit_stomp_headers.hrl, package.mk, src/rabbit_stomp_processor.erl, src/rabbit_stomp_util.erl, test/src/queue_properties.py, test/src/test.py, test/src/test_runner.py
=> Propagate x-headers in SEND and SUBSCRIBE to queue.declare

test/src/rabbit_stomp_test.erl
on OSX default max number of open file is 256 (ulimit -n)
=> decreased number of concurrent STOMP connections [fix #31]

src/rabbit_stomp_processor.erl, test/src/errors.py
send an ERROR frame, log the error and closes the consumer connection in case of duplicate subscription ID
related to #14 & #5
=> Manage duplicate subscription ID error

src/rabbit_stomp_reader.erl
This function includes operations that must be performed by
processes owning sockets.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/446
=> Use rabbit_net:accept_ack instead of ranch:accept_ack

src/rabbit_stomp_processor.erl
Allow passing 'undefined' instead of a fun for the start function.
When the processor receives this value, it simply uses 0,0 as the
heartbeat values which disables heartbeats completely and is
reported back to the client properly.
Fix for https://github.com/rabbitmq/rabbitmq-web-stomp/issues/28
=> Disable heartbeats when start fun is undefined

src/rabbit_stomp_processor.erl, src/rabbit_stomp_util.erl, test/src/destinations.py
=> Use 'durable' and 'persistent' interchangeably in more places

src/rabbit_stomp_reader.erl
of connection (flow control) state.
This makes it much easier to reason about flow control
state when looking at the management UI or monitoring tools
that poll HTTP API.
Now that rabbitmq/rabbitmq-management#41 is merged, there are
few arguments against always emitting stats.
Fixes #70.
=> Emit connection stats unconditionally

examples/perl/rabbitmq_stomp_rpc_client.pl
Currently, an example of stomp client `rabbitmq_stomp_rpc_client.pl` uses `/queue` destination to `reply-to` header.
But I think using the destination of `/temp-queue` is suitable than using `/queue` because
- `/temp-queue` accords with this use-case of RPC
- there is no example to use `/temp-queue`
Here is the result of using `/temp-queue` destination.
```bash
user@localhost:~/rabbitmq-stomp/examples/perl$ perl rabbitmq_stomp_rpc_client.pl 
Reply: Got body: request from /temp-queue/test
user@localhost:~/rabbitmq-stomp/examples/perl$ 
```
```bash
user@localhost:~/rabbitmq-stomp/examples/perl$ perl rabbitmq_stomp_rpc_service.pl 
Waiting for request...
Received message, reply_to = /reply-queue/amq.gen-yGAul0LiGSH75USKM_7SfQ
request from /temp-queue/test
Waiting for request...
```
=> Use '/temp-queue' destination instead of '/queue' for temporary-queues

src/rabbit_stomp_processor.erl, src/rabbit_stomp_reader.erl, test/src/rabbit_stomp_amqqueue_test.erl, test/src/rabbit_stomp_client.erl
Fixes #76 
Handle channel `{server_initiated_close, Code, Explanation}` errors same way as connection errors.
=> Handle channel errors in stomp_reader

include/rabbit_stomp.hrl, src/rabbit_stomp_processor.erl
This option forces the use of the default_login and
default_passcode when authenticating the user. It is
necessary for RabbitMQ-Web-STOMP's use_http_auth option.
Part of https://github.com/rabbitmq/rabbitmq-web-stomp/issues/43
=> Add a force_default_creds option

src/rabbit_stomp_client_sup.erl
Part of rabbitmq/rabbitmq-server#541
Replace `MAX_WAIT` with `WORKER_WAIT`
=> Set bounded timeout for OTP workers

src/rabbit_stomp_processor.erl
The old format is removed in Erlang 19.0, leading to build errors.
Also, get rid of the `use_specs` macro and thus always define `-spec()` & friends.
While here, unnify the style of `-type` and `-spec`.
References rabbitmq/rabbitmq-server#860.
[#118562897]
[#122335241]
=> Use the new -spec format

include/rabbit_stomp.hrl, src/rabbit_stomp.erl, src/rabbit_stomp_processor.erl, src/rabbit_stomp_reader.erl, test/connections_SUITE.erl, test/src/rabbit_stomp_client.erl
Backported part of https://github.com/rabbitmq/rabbitmq-stomp/commit/227447fc98b763da8399deabc944a1c59c3d9e45
Fixes the lack of connection pid on the stats (present since pre-3.6.7 releases), which might also cause a memory leak on the stats db.
Closes #102
=> Notify reductions, garbage_collection, recv_oct and send_oct in the core metrics

.gitignore, test/python_SUITE_data/src/amqp_headers.py, test/python_SUITE_data/src/base.py, test/python_SUITE_data/src/lifecycle.py, test/python_SUITE_data/src/test.py
Fixes #112 
Added test cases which show sending and receiving custom headers from STOMP -> STOMP as well as AMQP -> STOMP
=> Add tests demonstrating sending AMQP custom headers to STOMP subscriber

src/rabbit_stomp_util.erl
Fixes #115
Requires rabbitmq/rabbitmq-server#1262
It's unsafe to use `term_to_binary` to generate IDs like queue names,
because it can change in future erlang versions.
We cannot change queue generation algorithm, because queues can be durable
and renaming a queue is non-trivial in RabbtiMQ. So we use the compat function.
=> Generate queue names using compat function instead of term_to_binary.

src/rabbit_stomp_connection_info.erl, src/rabbit_stomp_reader.erl
This ensures that `rabbit_direct:maybe_call_connection_info_module` will not continuously return
`enoent`. In high connection churn scenarios, this can bring the node down because the number of Erlang processes will continuously grow.
=> Add rabbit_stomp_connection_info module

Makefile, priv/schema/rabbitmq_stomp.schema, src/rabbit_stomp_sup.erl
Bumps number of TLS connection acceptors to 10 by default. See rabbitmq/rabbitmq-server#1729
for context.
Part of rabbitmq/rabbitmq-server#1729.
[#161136615]
=> Use 10 TLS connection acceptors by default

priv/schema/rabbitmq_stomp.schema, test/config_schema_SUITE_data/rabbitmq_stomp.snippets
This introduces support for a number of `stomp.tcp_listen_options.*` settings in the new
style config format. They mimic `tcp_listen_options.*` available for AMQP 0-9-1 and AMQP 1.0 listeners.
Closes #129.
[#157922235]
=> New style config: support stomp.tcp_listen_options.*

include/rabbit_stomp_headers.hrl, src/rabbit_stomp_processor.erl, src/rabbit_stomp_reader.erl, src/rabbit_stomp_util.erl, test/python_SUITE.erl, test/python_SUITE_data/src/test.py, test/python_SUITE_data/src/x_queue_type_quorum.py
To be able to use quorum queues. Note deliveries from a classic queue
come with a context to inform back the queue about the handling of the
message (credit flow). Deliveries from a quorum queue do have this
context because quorum queues do not use credit flow. So supporting
quorum queues is not just about propagating the type header to AMQP
but needs also to handle both kinds of deliveries.
Fixes #138
(to merge when we know more about the motivation of using QQ with STOMP).
=> Support x-queue-type argument

Makefile, priv/schema/rabbitmq_stomp.schema, src/rabbit_stomp_processor.erl
👋
**Why:**
Various companies are using RMQ with third party software which doesn't offer the ability to alter the source code related to how the STOMP consumer behaves on the frame level, e.g. there's no possibility to actually change the frame `requeue` header to `false` as the frame is created by the 3rd party software.
This has proven to be an issue on a project I have been working on as the current stomp plugin frame `requeue` implementation defaults to `true` if the `requeue` header doesn't exist on the frame. The side-effect of this behaviour is that we ended in a loop of massive re-deliveries as the messages were always re-queued, while, what we wanted was to avoid re-queueing.
In order to get around this issue, we decided to expose the `stomp.default_nack_requeue` configuration …
=> Allow controlling nack requeue on plugin level

src/rabbit_stomp.erl, src/rabbit_stomp_internal_event_handler.erl, src/rabbit_stomp_reader.erl, src/rabbit_stomp_sup.erl
This makes the refs predictable and easy to compute
from a listener record. Then suspending all listeners
becomes a lot simpler.
While at it, make protocol applications clean up
their listeners when they stop. This way tests
and other callers that have to stop the app
would not need to know anything about
its listeners.
Part of rabbitmq/rabbitmq-server#2321
=> Maintenance mode event support
